version: 2

updates:
  # Updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 5
    target-branch: "master"
    schedule:
      interval: daily
      timezone: "Europe/Berlin"

  - directory: "/"
    package-ecosystem: docker
    reviewers:
      - "TUDOCK/devops"
    schedule:
      interval: weekly
