version: 2

updates:
  - directory: /
    package-ecosystem: github-actions
    reviewers:
      - "TUDOCK/devops"
    schedule:
      interval: daily

  - directory: "/"
    package-ecosystem: docker
    reviewers:
      - "TUDOCK/devops"
    schedule:
      interval: weekly
