version: 2

updates:
  - directory: /
    package-ecosystem: github-actions
    reviewers:
      - 'jeliebig'
    schedule:
      interval: daily

  - directory: "/"
    package-ecosystem: docker
    reviewers:
      - 'jeliebig'
    schedule:
      interval: weekly
