name: Build Docker image

on:
  pull_request:
    branches:
      - 'master'
  push:
   branches:
     - 'master'
  workflow_call:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_call' && 'master' || github.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Read version and revision info
        id: info
        run: |
          echo "version=$(cat VERSION | sed 's/release-//')" >> $GITHUB_OUTPUT
          echo "rev=$(cat REVISION)" >> $GITHUB_OUTPUT

      - name: Log in to the Container registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          context: ${{ github.event_name == 'workflow_call' && 'git' || 'workflow' }}
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: latest=${{ github.event_name != 'pull_request' && 'true' || 'false' }}
          tags: |
            type=raw,value=${{ steps.info.outputs.version }}.${{ steps.info.outputs.rev }},suffix=${{ github.event_name == 'pull_request' && github.event.number || '' }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
